"""
Tests for the survey JSON output produced by gen-survey-json.py.

Run with:
    conda run -n p312 python -m pytest tests/test_survey_data.py -v

Purpose
-------
These tests verify that the survey_data_proxy JSON files generated by
gen-survey-json.py satisfy the structural invariants described in
.github/instructions/survey_data.instructions.md.

Every assertion below can be verified by inspecting the generated
output/surveys/ files.  They are intentionally coarse-grained so that they
catch regressions caused by:
  - Changes to gen-survey-json.py logic
  - Changes to the upstream report-facts.json structure
  - Changes to the survey_data schema

When a test fails after a legitimate change, update the expected value here
AND note the change in scripts/gen-survey-json.py docstring.
"""

import json
from collections import Counter
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

SURVEYS_DIR = Path(__file__).parent.parent / "output" / "surveys"
COMBINED_PATH = SURVEYS_DIR / "survey_data_all.json"
REPORT_PATH = Path(__file__).parent.parent / "output" / "report-facts.json"


@pytest.fixture(scope="session")
def combined():
    """Load the combined survey_data_all.json (list of section wrappers)."""
    if not COMBINED_PATH.exists():
        pytest.skip(
            f"survey_data_all.json not found at {COMBINED_PATH}. "
            "Run gen-survey-json.py first."
        )
    with open(COMBINED_PATH, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="session")
def report():
    """Load the report-facts.json."""
    if not REPORT_PATH.exists():
        pytest.skip(
            f"report-facts.json not found at {REPORT_PATH}. "
            "Run parse-and-json.py first."
        )
    with open(REPORT_PATH, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="session")
def all_questions(combined) -> list[dict]:
    """Flat list of every question across all sections."""
    questions: list[dict] = []
    for section in combined:
        questions.extend(section.get("survey_data_proxy", []))
    return questions


@pytest.fixture(scope="session")
def per_section_questions() -> list[dict]:
    """Flat list of every question loaded from the individual per-section files."""
    if not SURVEYS_DIR.exists():
        pytest.skip(f"surveys directory not found at {SURVEYS_DIR}.")
    questions: list[dict] = []
    for path in sorted(SURVEYS_DIR.rglob("*.json")):
        if path.name in ("survey_index.json", "survey_data_all.json"):
            continue
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict):
            questions.extend(data.get("survey_data_proxy", []))
        elif isinstance(data, list):
            questions.extend(data)
    return questions


# ---------------------------------------------------------------------------
# TestConditionCriteriaPairing
# ---------------------------------------------------------------------------


class TestConditionCriteriaPairing:
    """condition and condition_criteria must always appear as a pair.

    Per survey_data.instructions.md, ``condition`` defines *when* a question
    is shown and ``condition_criteria`` defines *which values* of the
    referenced question(s) satisfy the condition.  One without the other is
    a bug — a condition without criteria cannot be evaluated, and criteria
    without a condition have no anchor.
    """

    def test_no_condition_without_criteria_combined(self, all_questions):
        """Every question with 'condition' in survey_data_all.json must also
        have 'condition_criteria'."""
        violations = [
            q["id"]
            for q in all_questions
            if "condition" in q and "condition_criteria" not in q
        ]
        assert violations == [], (
            f"{len(violations)} question(s) have 'condition' but no "
            f"'condition_criteria': {violations}"
        )

    def test_no_criteria_without_condition_combined(self, all_questions):
        """Every question with 'condition_criteria' in survey_data_all.json
        must also have 'condition'."""
        violations = [
            q["id"]
            for q in all_questions
            if "condition_criteria" in q and "condition" not in q
        ]
        assert violations == [], (
            f"{len(violations)} question(s) have 'condition_criteria' but no "
            f"'condition': {violations}"
        )

    def test_no_condition_without_criteria_per_section(self, per_section_questions):
        """Every question with 'condition' in per-section files must also
        have 'condition_criteria'."""
        violations = [
            q["id"]
            for q in per_section_questions
            if "condition" in q and "condition_criteria" not in q
        ]
        assert violations == [], (
            f"{len(violations)} question(s) have 'condition' but no "
            f"'condition_criteria': {violations}"
        )

    def test_no_criteria_without_condition_per_section(self, per_section_questions):
        """Every question with 'condition_criteria' in per-section files must
        also have 'condition'."""
        violations = [
            q["id"]
            for q in per_section_questions
            if "condition_criteria" in q and "condition" not in q
        ]
        assert violations == [], (
            f"{len(violations)} question(s) have 'condition_criteria' but no "
            f"'condition': {violations}"
        )

    def test_condition_and_criteria_counts_match(self, all_questions):
        """The number of questions with 'condition' must equal those with
        'condition_criteria'."""
        with_cond = sum(1 for q in all_questions if "condition" in q)
        with_crit = sum(1 for q in all_questions if "condition_criteria" in q)
        assert with_cond == with_crit, (
            f"Mismatch: {with_cond} questions with 'condition' vs "
            f"{with_crit} with 'condition_criteria'"
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_section_survey(section_id: str) -> dict:
    """Load a per-section survey JSON file."""
    # Search for the file in all sheet subdirectories
    for path in SURVEYS_DIR.rglob(f"{section_id}.json"):
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    pytest.skip(f"Section file {section_id}.json not found under {SURVEYS_DIR}")


# ---------------------------------------------------------------------------
# TestB7MassFlowSurvey
# ---------------------------------------------------------------------------


class TestB7MassFlowSurvey:
    """Survey output tests for the b7_annual_mass_flow section.

    This section has a yellow-cell trigger, an expandable table
    (with additional_rows_warning), and summary/total rows.
    """

    @pytest.fixture(scope="class")
    def mass_flow(self):
        return _load_section_survey(
            "b7_annual_mass_flow_of_relevant_materials_used"
        )

    @pytest.fixture(scope="class")
    def questions(self, mass_flow):
        return mass_flow["survey_data_proxy"]

    def test_question_count(self, questions):
        """6 questions: 1 trigger + 3 dynamic table (name, mass/vol, unit)
        + 2 summary totals.  Mass/Volume is a single item (Weight + Volume
        share the same column label and are collapsed)."""
        assert len(questions) == 6

    def test_trigger_is_first(self, questions):
        """The yellow-cell trigger question must be first."""
        meta = questions[0].get("_meta", {})
        assert meta.get("source") == "yellowCell"
        assert questions[0]["answer_type"] == "RADIO"

    def test_table_data_before_summaries(self, questions):
        """Table data fields (NameOfMaterialUsed, Weight/Volume) must appear
        before summary/total fields (TotalMass/Volume).  After column-label
        dedup, only WeightOfMaterialUsed survives (VolumeOfMaterialUsed
        shares the same column and is collapsed)."""
        table_qnames = {
            "vsme:NameOfMaterialUsed",
            "vsme:WeightOfMaterialUsed",
        }
        summary_qnames = {
            "vsme:TotalMassOfMaterialUsed",
            "vsme:TotalVolumeOfMaterialUsed",
        }

        table_indices = [
            i
            for i, q in enumerate(questions)
            if q.get("_meta", {}).get("xbrl_qname") in table_qnames
        ]
        summary_indices = [
            i
            for i, q in enumerate(questions)
            if q.get("_meta", {}).get("xbrl_qname") in summary_qnames
        ]

        assert len(table_indices) >= 2
        assert len(summary_indices) == 2
        assert max(table_indices) < min(summary_indices), (
            f"Table fields at {table_indices} should all precede "
            f"summary fields at {summary_indices}"
        )

    def test_no_display_only_unit_fields(self, questions):
        """Display-only unit fields (TotalMass/VolumeOfMaterialUsed_unit)
        should be excluded — they have no options."""
        unit_field_ids = [
            q.get("_meta", {}).get("source_field_id", "")
            for q in questions
        ]
        assert "TotalMassOfMaterialUsed_unit" not in unit_field_ids
        assert "TotalVolumeOfMaterialUsed_unit" not in unit_field_ids

    def test_unit_selection_has_options(self, questions):
        """The shared unit selection field must have answer options."""
        unit_qs = [
            q for q in questions if q["answer_type"] == "DROPDOWN"
            and q.get("answer_options")
        ]
        assert len(unit_qs) >= 1, "Expected at least 1 DROPDOWN with options"

    def test_summary_totals_are_numeric(self, questions):
        """TotalMass and TotalVolume fields must be NUMERIC."""
        summary_qnames = {
            "vsme:TotalMassOfMaterialUsed",
            "vsme:TotalVolumeOfMaterialUsed",
        }
        summaries = [
            q
            for q in questions
            if q.get("_meta", {}).get("xbrl_qname") in summary_qnames
        ]
        assert len(summaries) == 2
        for q in summaries:
            assert q["answer_type"] == "NUMERIC"

    def test_no_duplicate_names(self, questions):
        """No two questions should share the same name."""
        from collections import Counter

        names = Counter(q["name"] for q in questions)
        dupes = {n: c for n, c in names.items() if c > 1}
        assert dupes == {}, f"Duplicate question names: {dupes}"

    def test_mass_volume_is_single_item(self, questions):
        """The 'Mass / Volume' column must produce exactly one survey
        question (Weight + Volume share the same column label and the
        unit dropdown determines interpretation)."""
        mass_vol_qs = [
            q for q in questions if q["name"] == "Mass / Volume"
        ]
        assert len(mass_vol_qs) == 1, (
            f"Expected 1 'Mass / Volume' question, got {len(mass_vol_qs)}"
        )

    def test_dynamic_group_on_table_fields(self, questions):
        """Table fields (name, mass/volume, unit) must be in a dynamic
        group; trigger and summary totals must not."""
        dynamic_qs = [q for q in questions if "__DQ0" in q["id"]]
        static_qs = [q for q in questions if "__DQ0" not in q["id"]]

        # 3 dynamic: Name, Mass/Volume, Unit
        assert len(dynamic_qs) == 3, (
            f"Expected 3 dynamic questions, got {len(dynamic_qs)}: "
            f"{[q['name'] for q in dynamic_qs]}"
        )
        # All share the same group_id
        group_ids = {q["dynamic_group_id"] for q in dynamic_qs}
        assert len(group_ids) == 1

        # 3 static: trigger + 2 totals
        assert len(static_qs) == 3
        # Trigger is the yellow cell
        assert static_qs[0].get("_meta", {}).get("source") == "yellowCell"

    def test_dynamic_group_header(self, questions):
        """Dynamic group header should be 'Material'."""
        dynamic_qs = [q for q in questions if "__DQ0" in q["id"]]
        for q in dynamic_qs:
            assert q["dynamic_header"] == "Material"

    def test_dynamic_tag_expression(self, questions):
        """Tag expression should reference the NameOfMaterialUsed field."""
        dynamic_qs = [q for q in questions if "__DQ0" in q["id"]]
        tag_exprs = {q.get("dynamic_tag_expression", "") for q in dynamic_qs}
        # All should have the same tag expression
        assert len(tag_exprs) == 1
        tag_expr = tag_exprs.pop()
        assert tag_expr, "dynamic_tag_expression should not be empty"
        # Should reference a DQ0 ID
        assert "__DQ0" in tag_expr


# ---------------------------------------------------------------------------
# TestB4PollutionSurvey
# ---------------------------------------------------------------------------


class TestB4PollutionSurvey:
    """Survey output tests for the b4_pollution_of_air_water_and_soil section.

    Expected layout (8 questions):
      [0]     RADIO      Is the undertaking already required… (trigger)
      [1]     RADIO      Is this disclosure already publicly available?
      [2]     OPEN       Please provide the relevant URL…
      [3]     DROPDOWN   Please select the unit… (section-wide, NOT dynamic)
      [4] DYN DROPDOWN   Pollutant (synthetic from enum_ListPollutants)
      [5] DYN NUMERIC    Emission to air
      [6] DYN NUMERIC    Emission to water
      [7] DYN NUMERIC    Emission to soil
    """

    @pytest.fixture(scope="class")
    def pollution(self):
        return _load_section_survey("b4_pollution_of_air_water_and_soil")

    @pytest.fixture(scope="class")
    def questions(self, pollution):
        return pollution["survey_data_proxy"]

    def test_question_count(self, questions):
        """8 questions: 3 static rowLabel + 1 section-wide unit + 4 dynamic."""
        assert len(questions) == 8

    def test_static_questions_first(self, questions):
        """First 4 questions must be static (no __DQ0 suffix)."""
        for i in range(4):
            assert "__DQ0" not in questions[i]["id"], (
                f"Question {i} should be static, got id={questions[i]['id']}"
            )

    def test_dynamic_questions_last(self, questions):
        """Last 4 questions must be dynamic (__DQ0 suffix)."""
        for i in range(4, 8):
            assert "__DQ0" in questions[i]["id"], (
                f"Question {i} should be dynamic, got id={questions[i]['id']}"
            )

    def test_trigger_is_first(self, questions):
        """The yellow-cell trigger question must be first."""
        meta = questions[0].get("_meta", {})
        assert meta.get("source") == "yellowCell"
        assert questions[0]["answer_type"] == "RADIO"

    def test_unit_is_section_wide_not_dynamic(self, questions):
        """The 'Please select the unit…' dropdown must be static
        (section-wide), not part of the dynamic group."""
        unit_q = None
        for q in questions:
            if "select the unit" in q["name"].lower():
                unit_q = q
                break
        assert unit_q is not None, "Unit selection question not found"
        assert "__DQ0" not in unit_q["id"], (
            "Unit field should be static (section-wide), not dynamic"
        )
        assert unit_q["answer_type"] == "DROPDOWN"

    def test_pollutant_is_dynamic_dropdown(self, questions):
        """The Pollutant field must be a dynamic DROPDOWN with options
        from enum_ListPollutants."""
        pollutant_qs = [q for q in questions if q["name"] == "Pollutant"]
        assert len(pollutant_qs) == 1, (
            f"Expected 1 Pollutant question, got {len(pollutant_qs)}"
        )
        pq = pollutant_qs[0]
        assert "__DQ0" in pq["id"]
        assert pq["answer_type"] == "DROPDOWN"
        opts = pq.get("answer_options", [])
        assert len(opts) > 50, f"Expected 50+ pollutant options, got {len(opts)}"

    def test_emission_columns_are_dynamic_numeric(self, questions):
        """Emission to air/water/soil must be dynamic NUMERIC fields."""
        emission_names = {"Emission to air", "Emission to water", "Emission to soil"}
        emission_qs = [q for q in questions if q["name"] in emission_names]
        assert len(emission_qs) == 3, (
            f"Expected 3 emission questions, got {len(emission_qs)}"
        )
        for eq in emission_qs:
            assert "__DQ0" in eq["id"]
            assert eq["answer_type"] == "NUMERIC"

    def test_dynamic_group_properties(self, questions):
        """All dynamic questions share the same group ID and header."""
        dynamic_qs = [q for q in questions if "__DQ0" in q["id"]]
        assert len(dynamic_qs) == 4

        group_ids = {q["dynamic_group_id"] for q in dynamic_qs}
        assert len(group_ids) == 1

        for q in dynamic_qs:
            assert q["dynamic_header"] == "Pollutant"

    def test_dynamic_tag_references_pollutant(self, questions):
        """Tag expression should reference the Pollutant field's DQ0 ID."""
        dynamic_qs = [q for q in questions if "__DQ0" in q["id"]]
        pollutant_id = next(
            q["id"] for q in dynamic_qs if q["name"] == "Pollutant"
        )
        for q in dynamic_qs:
            tag = q.get("dynamic_tag_expression", "")
            assert tag == f"{{{pollutant_id}}}", (
                f"Expected tag expression '{{{pollutant_id}}}', got '{tag}'"
            )

    def test_no_duplicate_names(self, questions):
        """No two questions should share the same name."""
        from collections import Counter

        names = Counter(q["name"] for q in questions)
        dupes = {n: c for n, c in names.items() if c > 1}
        assert dupes == {}, f"Duplicate question names: {dupes}"


# ---------------------------------------------------------------------------
# TestB7WasteSurvey
# ---------------------------------------------------------------------------


class TestB7WasteSurvey:
    """Survey output tests for the b7_waste_generated section.

    Expected layout (12 questions):
      [0]     DROPDOWN   Unit selection (section-wide, NOT dynamic)
      [1] DYN DROPDOWN   Type of waste (synthetic from enum_ListTypeOfWastes)
      [2] DYN NUMERIC    Waste diverted to recycle or reuse
      [3] DYN NUMERIC    Waste directed to disposal
      [4] DYN NUMERIC    Amount of waste recycled reused and directed to disposal
      [5-11]  ...        Summary totals (static)
    """

    @pytest.fixture(scope="class")
    def waste(self):
        return _load_section_survey("b7_waste_generated")

    @pytest.fixture(scope="class")
    def questions(self, waste):
        return waste["survey_data_proxy"]

    def test_question_count(self, questions):
        """12 questions: 1 section-wide unit + 4 dynamic table + 7 summary."""
        assert len(questions) == 12

    def test_type_of_waste_is_dynamic_dropdown(self, questions):
        """Type of waste must be a dynamic DROPDOWN with enum options."""
        tow_qs = [q for q in questions if q["name"] == "Type of waste"]
        assert len(tow_qs) == 1
        tow = tow_qs[0]
        assert "__DQ0" in tow["id"]
        assert tow["answer_type"] == "DROPDOWN"
        opts = tow.get("answer_options", [])
        assert len(opts) > 5, f"Expected 5+ waste type options, got {len(opts)}"

    def test_unit_is_section_wide(self, questions):
        """The unit dropdown must be static (no __DQ0)."""
        unit_qs = [
            q for q in questions
            if "unit selection" in q["name"].lower()
        ]
        assert len(unit_qs) >= 1
        for uq in unit_qs:
            assert "__DQ0" not in uq["id"], (
                "Unit field should be static (section-wide), not dynamic"
            )

    def test_dynamic_count(self, questions):
        """4 dynamic questions: type_of_waste + 3 waste columns."""
        dynamic_qs = [q for q in questions if "__DQ0" in q["id"]]
        assert len(dynamic_qs) == 4, (
            f"Expected 4 dynamic questions, got {len(dynamic_qs)}: "
            f"{[q['name'] for q in dynamic_qs]}"
        )

    def test_dynamic_tag_references_waste_type(self, questions):
        """Tag expression should reference the Type of waste field."""
        dynamic_qs = [q for q in questions if "__DQ0" in q["id"]]
        type_id = next(
            q["id"] for q in dynamic_qs if q["name"] == "Type of waste"
        )
        for q in dynamic_qs:
            tag = q.get("dynamic_tag_expression", "")
            assert tag == f"{{{type_id}}}", (
                f"Expected tag '{{{type_id}}}', got '{tag}'"
            )


# ---------------------------------------------------------------------------
# TestXbrlSurveyCoverage
# ---------------------------------------------------------------------------


# XBRL qnames from report-facts.json that are intentionally NOT represented
# as individual survey questions.  Each is paired with the qname that IS in
# the survey and covers the same column (the unit dropdown determines which
# interpretation applies at runtime).
#
# When the dedup strategy changes, update this dict accordingly.
_COLUMN_DEDUP_COLLAPSED: dict[str, str] = {
    # b7_annual_mass_flow: Volume collapsed into Weight (same "mass_volume" column)
    "vsme:VolumeOfMaterialUsed": "vsme:WeightOfMaterialUsed",
    # b7_waste_generated: Mass/Volume alternates within same column
    "vsme:WasteDivertedToRecycleOrReuseMass": "vsme:WasteDivertedToRecycleOrReuseVolume",
    "vsme:WasteDirectedToDisposalVolume": "vsme:WasteDirectedToDisposalMass",
    "vsme:TotalWasteRecycledReusedAndDirectedToDisposalMass": "vsme:TotalWasteRecycledReusedAndDirectedToDisposalVolume",
}


class TestXbrlSurveyCoverage:
    """Every XBRL fact qname in report-facts.json must appear in the
    survey output (via ``_meta.xbrl_qname``), or be a known column-dedup
    collapse whose counterpart IS in the survey.

    This catches regressions where gen-survey-json.py accidentally drops
    an XBRL concept from the survey output.
    """

    @pytest.fixture(scope="class")
    def report_xbrl_qnames(self, report) -> set[str]:
        """Unique XBRL qnames across all report-facts sections."""
        qnames: set[str] = set()
        for section in report.get("sections", []):
            for field in section.get("fields", []):
                qn = field.get("qname", "")
                if qn:
                    qnames.add(qn)
        return qnames

    @pytest.fixture(scope="class")
    def survey_xbrl_qnames(self, combined) -> set[str]:
        """Unique XBRL qnames across all survey questions."""
        qnames: set[str] = set()
        for section in combined:
            for q in section.get("survey_data_proxy", []):
                xq = q.get("_meta", {}).get("xbrl_qname", "")
                if xq:
                    qnames.add(xq)
        return qnames

    def test_report_qname_count(self, report_xbrl_qnames):
        """Guard-rail: expected number of unique XBRL qnames in report-facts."""
        assert len(report_xbrl_qnames) == 141

    def test_survey_qname_count(self, survey_xbrl_qnames):
        """Guard-rail: expected number of unique XBRL qnames in survey."""
        assert len(survey_xbrl_qnames) == 137

    def test_collapsed_count(self):
        """Guard-rail: the number of known column-dedup collapsed qnames."""
        assert len(_COLUMN_DEDUP_COLLAPSED) == 4

    def test_all_report_qnames_covered_by_survey(
        self, report_xbrl_qnames, survey_xbrl_qnames
    ):
        """Every XBRL qname from report-facts must be in the survey or in
        the known column-dedup collapsed set."""
        uncovered = []
        for qn in sorted(report_xbrl_qnames):
            if qn in survey_xbrl_qnames:
                continue
            if qn in _COLUMN_DEDUP_COLLAPSED:
                continue
            uncovered.append(qn)

        if uncovered:
            detail = "\n".join(f"  {qn}" for qn in uncovered)
            pytest.fail(
                f"{len(uncovered)} XBRL qname(s) from report-facts are not "
                f"represented in the survey output:\n{detail}\n\n"
                f"If intentionally collapsed by column-dedup, add them to "
                f"_COLUMN_DEDUP_COLLAPSED with their surviving counterpart."
            )

    def test_collapsed_counterparts_are_in_survey(self, survey_xbrl_qnames):
        """Every collapsed qname's counterpart must actually be in the survey."""
        missing_counterparts = []
        for collapsed, survivor in _COLUMN_DEDUP_COLLAPSED.items():
            if survivor not in survey_xbrl_qnames:
                missing_counterparts.append((collapsed, survivor))

        if missing_counterparts:
            detail = "\n".join(
                f"  {c} → counterpart {s} NOT in survey"
                for c, s in missing_counterparts
            )
            pytest.fail(
                f"{len(missing_counterparts)} collapsed qname(s) have "
                f"counterparts missing from the survey:\n{detail}"
            )

    def test_collapsed_are_actually_missing(
        self, report_xbrl_qnames, survey_xbrl_qnames
    ):
        """Every entry in _COLUMN_DEDUP_COLLAPSED must genuinely be absent
        from the survey.  If the qname starts appearing, remove it from the
        dict."""
        false_collapsed = [
            qn
            for qn in _COLUMN_DEDUP_COLLAPSED
            if qn in survey_xbrl_qnames
        ]
        if false_collapsed:
            detail = "\n".join(f"  {qn}" for qn in false_collapsed)
            pytest.fail(
                f"{len(false_collapsed)} _COLUMN_DEDUP_COLLAPSED entries are "
                f"now in the survey — remove them:\n{detail}"
            )

    def test_no_survey_qname_outside_report(
        self, report_xbrl_qnames, survey_xbrl_qnames
    ):
        """Every XBRL qname in the survey must originate from report-facts.
        Synthetic fields (no qname) are excluded from this check."""
        extra = survey_xbrl_qnames - report_xbrl_qnames
        if extra:
            detail = "\n".join(f"  {qn}" for qn in sorted(extra))
            pytest.fail(
                f"{len(extra)} XBRL qname(s) in survey have no corresponding "
                f"field in report-facts:\n{detail}"
            )
